name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install e Test - pedidos
        run: |
          cd pedidos
          npm install
          npm test

      - name: Install e Test - pagamentos
        run: |
          cd pagamentos
          npm install
          npm test

      - name: Install e Test - estoque
        run: |
          cd estoque
          npm install
          npm test

      - name: Install e Test - gateway
        run: |
          cd gateway
          npm install
          npm test

      - name: Build Docker Compose
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: docker compose build